import crypto from 'node:crypto'
import { sendText, userManager } from '#helper'
import { saveMessage, getStoredMessage } from '#cache'

function randomName(len = 6) {
  return crypto.randomBytes(len).toString('hex')
}

async function handler({ m, jid, sock }) {
  if (!userManager.trustedJids.has(m.senderId)) return
  if (!m.q) return sendText(sock, jid, 'reply pesan yang mau dijadikan crm', m)

  const q = m.q
  const name = q.type || 'message'

  try {
    // simpan pesan ke store dan ambil id
    const id = await saveMessage(q)
    if (!id) return sendText(sock, jid, 'gagal menyimpan message', m)

    // ambil pesan lengkap dari store
    const stored = getStoredMessage(id)
    if (!stored) return sendText(sock, jid, 'message tidak ditemukan di store', m)

    // susun content relay (pakai message dari store biar favicon ikut)
    const content = { ...stored.message }

    // kalau ada favicon metadata, tempelkan
    if (stored.faviconMMSMetadata) {
      if (content.extendedTextMessage) {
        content.extendedTextMessage.contextInfo = {
          ...(content.extendedTextMessage.contextInfo || {}),
          ...stored.faviconMMSMetadata
        }
      }
    }

    // stringify hasil akhir
    const rawContent = JSON.stringify(content, null, 2)

    const fileContent = `/* this message was generated by wolep bot
remember to change sock and jid variable
*/

const content = ${rawContent}

const relayOption = {}

await sock.relayMessage(jid, content, relayOption)
`

    const fileName = `${name}-${randomName(4)}.js`

    await sock.sendMessage(
      jid,
      {
        document: Buffer.from(fileContent),
        fileName,
        mimetype: 'application/javascript'
      },
      { quoted: m }
    )

  } catch (e) {
    console.error(e)
    await sendText(sock, jid, `error:\n${e.message}`, m)
  }
}

handler.pluginName = 'developer-crm'
handler.command = ['crm']
handler.category = ['developer']
handler.deskripsi = 'create relay message script (full metadata)'
handler.meta = {
  fileName: 'developer-crm.js',
  version: '1.3.0',
  author: 'Kado'
}

export default handler